services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db_tcp
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=BD_SPASIBO_1
    ports:
      - "4647:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
      build: .
      container_name: spring_app_tcp
      restart: unless-stopped
      depends_on:
        - db
      ports:
        - "8081:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=default
      volumes:
        - ./logs:/app/logs
volumes:
  postgres-data:
