spring:
  datasource:
    # url: jdbc:postgresql://localhost:4647/BD_SPASIBO_1
    url: jdbc:postgresql://postgres_db_tcp:5432/BD_SPASIBO_1  # Изменено с localhost на имя контейнера
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  application:
    name: BD_SPASIBO_1_idea

  thymeleaf:
    cache: false

  messages:
    basename: messages

server:
  port: 8080

security:
  jwt:
    secret: U3VwZXJTZWN1cmVLZXlXaXRoNTY0Qml0c0FuZEJhc2U2NEVuY29kaW5nIQ==ghkfccrLLLtp6437dndcuyGFCCgcyeuclGgvcskjcGCFuvfesvbs
    access: 86400000


logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
